### ISSUE TITLE
responsefiletemplate file handling doesn't do any security checks?

### ISSUE THREAD

**Issue by danmarsden** [Wunderbyte-GmbH/moodle_qtype_jack#9]
https://github.com/Wunderbyte-GmbH/moodle_qtype_jack/blob/main/lib.php#L46C24-L46C44

typically you pass this through question_pluginfile which does the login/capability checks - should all responsefiletemplate items be available anonymously to all users no matter if they are able to veiwe the course or context the file is from?

**Comment by georgmaisser** [comment]
@danmarsden Hi Dan, thank you very much for your input. I think we fixed all the issues you raised and would be very grateful for a second look. We will think of your hard look on all the details, especially security, and go back to the rest of our plugins and evaluate, where we can improve them. All the best!

**Comment by danmarsden** [comment]
Great! - can you please upload the new version to the plugins db and hit the request re-approval button on the developer zone tab to add it back into the review queue - then ping me on the tracker issue associated with the review so I remember to come back to it?

thanks!
